// gen-icons.mjs — the committed Phosphor subset (epic #295 ticket #305; architecture § Stack
// "Icons ship as a generated subset, never a library", G8).
// Copies the path data of the names listed in system/icons.manifest.json out of
// tooling/icons/node_modules/@phosphor-icons/core into a generated system/icons.mjs, which is the
// ONLY source the `icon` template reads. No shipped page ever loads the package; no icon library
// ships; nothing is vendored beyond the named set.
//   node agent-layer/gen-icons.mjs              emit system/icons.mjs
//   node agent-layer/gen-icons.mjs --check      CI drift leg — writes nothing
//   node agent-layer/gen-icons.mjs --add <name> append to the manifest, then emit
// Paths resolve from this module (NOT cwd) — build.mjs runs from the jobs folder.
//
// FAILS CLOSED. A missing tooling/icons/node_modules THROWS naming the directory rather than
// reporting "no drift" — a check that passes because it reached nothing is this repo's largest
// class of defect (.claude/references/gates.md; the check that cannot fail).
//
// REFUSES AN UNEXPECTED SVG SHAPE. Observed over all 1512 regular-weight icons at 2.1.1: every one
// is exactly one <path>, viewBox "0 0 256 256", fill="currentColor", with no circle/rect/line/g.
// A package bump that changes that must be a loud failure, never a half-copied glyph.

import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const MANIFEST = "system/icons.manifest.json";
const DEST = "system/icons.mjs";
const PKG = "tooling/icons/node_modules/@phosphor-icons/core";
// The one shape this generator accepts, pinned so a package bump cannot widen it silently.
const VIEWBOX = "0 0 256 256";

const assetDir = (weight) => join(ROOT, PKG, "assets", weight);

// The package on disk, or a throw naming the directory and the fix.
function requirePackage(weight) {
  const dir = assetDir(weight);
  if (!existsSync(dir))
    throw new Error(
      `gen-icons: ${PKG}/assets/${weight} is missing — the icon subset cannot be regenerated or checked. ` +
        `Install it: cd tooling/icons && npm ci`
    );
  return dir;
}

// One SVG file → its single path `d`. Throws, naming the file, on any shape but the pinned one.
export function pathOf(svg, file) {
  const vb = /viewBox="([^"]*)"/.exec(svg);
  if (!vb || vb[1] !== VIEWBOX)
    throw new Error(`gen-icons: ${file} declares viewBox ${JSON.stringify(vb && vb[1])}, expected "${VIEWBOX}" — the package's shape moved`);
  const paths = [...svg.matchAll(/<path\b[^>]*\bd="([^"]*)"/g)].map((m) => m[1]);
  if (paths.length !== 1)
    throw new Error(`gen-icons: ${file} carries ${paths.length} <path> elements, expected exactly 1 — the package's shape moved`);
  const others = /<(circle|rect|line|polyline|polygon|ellipse|g)\b/.exec(svg);
  if (others)
    throw new Error(`gen-icons: ${file} carries a <${others[1]}> — this generator emits one path per icon and would drop it`);
  if (!paths[0].startsWith("M"))
    throw new Error(`gen-icons: ${file}'s path data does not start with a moveto — refusing to emit it`);
  return paths[0];
}

// The emitted text, from a manifest and a reader. PURE — exported so tooling/build-checks.mjs can
// drive it over a mutated manifest without writing to disk (the validateExamples precedent).
export function emitIcons(manifest, readIcon) {
  const names = [...manifest.icons];
  const sorted = [...names].sort();
  if (names.join("\u0000") !== sorted.join("\u0000"))
    throw new Error(`gen-icons: ${MANIFEST} "icons" is not sorted — the emitted map's key order is the manifest's, so an unsorted manifest is a churning artifact`);
  if (new Set(names).size !== names.length)
    throw new Error(`gen-icons: ${MANIFEST} "icons" carries a duplicate name`);
  const lines = names.map((n) => `  ${JSON.stringify(n)}: ${JSON.stringify(readIcon(n))},`);
  return [
    `// system/icons.mjs — GENERATED by agent-layer/gen-icons.mjs — do not edit.`,
    `// The committed Phosphor subset (epic #295 ticket #305, G8): the ${names.length} glyph(s) named in`,
    `// system/icons.manifest.json, at the "${manifest.weight}" weight, and nothing else. Add one with:`,
    `//   node agent-layer/gen-icons.mjs --add <phosphor-name>`,
    `//`,
    `// Phosphor Icons — MIT License, Copyright (c) 2023 Phosphor Icons.`,
    `// https://github.com/phosphor-icons/core — the full licence ships in tooling/icons/node_modules.`,
    `// Recorded ONCE, here: this file is the only place any of that artwork lives in this repo.`,
    ``,
    `export const ICON_VIEWBOX = ${JSON.stringify(VIEWBOX)};`,
    ``,
    `export const ICONS = Object.freeze({`,
    ...lines,
    `});`,
    ``,
  ].join("\n");
}

// PURE — text in, manifest out, no fs. Exported for the same reason emitIcons is (validateExamples'
// precedent): all three of its refusals can then be DRIVEN by build-checks over synthetic strings,
// which is the only thing that proves they can fail at all. readManifest is the fs half and nothing
// more. The parse throw names the path like the two validation throws below it — a bare SyntaxError
// says "position 2" and never WHICH file, and this chain carries a dozen generated JSON artifacts a
// reader could be looking at instead (CLAUDE.md's Errors ground rule: name the offending path).
export function parseManifest(text) {
  let m;
  try { m = JSON.parse(text); }
  catch (e) { throw new Error(`gen-icons: ${MANIFEST} is not valid JSON — ${e.message}`); }
  if (typeof m.weight !== "string" || !m.weight)
    throw new Error(`gen-icons: ${MANIFEST} needs a non-empty "weight"`);
  if (!Array.isArray(m.icons) || !m.icons.length || !m.icons.every((n) => typeof n === "string" && /^[a-z0-9-]+$/.test(n)))
    throw new Error(`gen-icons: ${MANIFEST} "icons" must be a non-empty array of lowercase Phosphor names`);
  return m;
}

export function readManifest() {
  return parseManifest(readFileSync(join(ROOT, MANIFEST), "utf8"));
}

// Emit the artifact (or, with {check: true}, compare against disk and report drift).
// Returns { icons (count), drifted (file names, check mode only) }.
export function genIcons({ check = false } = {}) {
  const manifest = readManifest();
  const dir = requirePackage(manifest.weight);
  const readIcon = (name) => {
    const file = join(dir, `${name}.svg`);
    if (!existsSync(file))
      throw new Error(`gen-icons: "${name}" has no ${manifest.weight}-weight SVG in ${PKG} — check the name at phosphoricons.com ("back" is arrow-left, "close" is x, "chevron-right" is caret-right)`);
    return pathOf(readFileSync(file, "utf8"), `${name}.svg`);
  };
  const out = emitIcons(manifest, readIcon);
  if (check) {
    let prior;
    try { prior = readFileSync(join(ROOT, DEST), "utf8"); } catch { prior = ""; }
    return { icons: manifest.icons.length, drifted: prior !== out ? [DEST] : [] };
  }
  writeFileSync(join(ROOT, DEST), out);
  return { icons: manifest.icons.length, drifted: [] };
}

// --add <name> — the one command G8 asks for. Refuses a name the package does not carry, naming a
// near miss where there is one; a name already present is a stated no-op, never a duplicate line.
export function addIcon(name) {
  if (typeof name !== "string" || !/^[a-z0-9-]+$/.test(name))
    throw new Error(`gen-icons --add: ${JSON.stringify(name)} is not a Phosphor name (lowercase letters, digits and hyphens)`);
  const manifest = readManifest();
  const dir = requirePackage(manifest.weight);
  if (!existsSync(join(dir, `${name}.svg`))) {
    // A near miss is a name that SHARES A WHOLE WORD, never a substring: "chevron-right" must
    // suggest caret-right and arrow-right, and substring matching suggested "t-shirt" (because
    // "chevron-right".includes("t")), which is worse than saying nothing. Measured while writing it.
    const want = new Set(name.split("-"));
    const near = readdirSync(dir)
      .filter((f) => f.endsWith(".svg"))
      .map((f) => f.slice(0, -4))
      .filter((n) => n.split("-").some((w) => want.has(w)))
      .sort((a, b) => a.length - b.length || (a < b ? -1 : 1))
      .slice(0, 5);
    throw new Error(
      `gen-icons --add: "${name}" has no ${manifest.weight}-weight SVG in ${PKG}` +
        (near.length ? ` — did you mean ${near.join(", ")}?` : " — check the name at phosphoricons.com")
    );
  }
  if (manifest.icons.includes(name)) return { added: false, icons: manifest.icons.length };
  const next = { ...manifest, icons: [...manifest.icons, name].sort() };
  // Re-serialised from the PARSED object so the file stays canonical — two-space indent, keys in
  // their declared order, one trailing newline — rather than spliced into the existing text.
  writeFileSync(join(ROOT, MANIFEST), `${JSON.stringify(next, null, 2)}\n`);
  return { added: true, icons: next.icons.length };
}

// pathToFileURL, not `file://${argv[1]}`: this repo's path contains a space, which
// import.meta.url percent-encodes — the naive comparison never matches.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    const args = process.argv.slice(2);
    const addAt = args.indexOf("--add");
    if (addAt !== -1) {
      const name = args[addAt + 1];
      const r = addIcon(name);
      console.log(r.added ? `icons +   "${name}" added to ${MANIFEST} (${r.icons} icons)` : `icons =   "${name}" is already in ${MANIFEST} (${r.icons} icons) — nothing to do`);
    }
    const check = args.includes("--check");
    const r = genIcons({ check });
    if (check && r.drifted.length) {
      console.error(`icons ✗  drift: ${r.drifted.join(", ")} — regenerate with: node agent-layer/gen-icons.mjs`);
      process.exit(1);
    }
    console.log(`icons ✓  ${r.icons} icons ${check ? "— no drift" : `(${DEST})`}`);
  } catch (e) {
    console.error(`icons ✗  ${e.message}`);
    process.exit(1);
  }
}
