// gen-handoff.mjs — ComponentSpecs + DataContracts + tokens → the handoff pack
// (epic #1, tickets #7 + #12). Spec: docs/epics/ai-first-ux-factory.architecture.md §Data model.
// Emits handoff/verdant/: pack.json (spec heads + prose + portability block, inlined for
// the viewer), verbatim DataContracts, the DTCG source, Style Dictionary css/ios/android
// builds, the wc/ custom-element wrappers + README, and figma-import.md. figma-parity.json
// is NOT emitted here — the parity script writes it (secret + network; this chain stays
// deterministic) and this generator never touches it.
// contracts/ and wc/ are rebuilt from scratch each run (rmSync): they are entirely owned by
// this generator — one sidecar per spec / per wrapper — so a spec or wrapper removed at source
// leaves no orphaned sidecar behind. A stale, already-committed sidecar is byte-identical to
// HEAD, so the drift gate's porcelain check can't see it and it would ship silently in the pack
// + pack.bundle.json (#64). The clean-slate is scoped to those two dirs only — the top-level,
// real-run-only figma-parity.json is never at risk.
// Standalone:  node agent-layer/gen-handoff.mjs
// Paths resolve from this module (NOT cwd) — build.mjs runs from the jobs folder.

import { copyFileSync, existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { execFileSync } from "node:child_process";
import { parseComponentSpec } from "./lib.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SPECS = join(ROOT, "system/specs");
const DEST = join(ROOT, "handoff/verdant");
const SD_BUILD = join(ROOT, "tooling/style-dictionary/build-tokens.mjs");
const WC_SRC = join(ROOT, "system/wc");
const FIGMA_DOC = join(ROOT, "system/figma-import.md");

export function genHandoff() {
  const files = readdirSync(SPECS).filter((f) => f.endsWith(".md")).sort();
  const specs = files.map((f) => parseComponentSpec(join(SPECS, f)));

  const names = new Set(specs.map((s) => s.head.component));
  for (const s of specs) {
    for (const child of s.head.children) {
      if (!names.has(child)) throw new Error(`${s.path}: children entry "${child}" names no spec in system/specs/`);
    }
  }

  // Multi-target token builds — child process so agent-layer stays zero-dep
  // (tooling/style-dictionary owns the one allowed dependency).
  try {
    execFileSync(process.execPath, [SD_BUILD], { stdio: "inherit" });
  } catch {
    throw new Error(`${SD_BUILD}: Style Dictionary build failed — if node_modules is missing, run: cd tooling/style-dictionary && npm install`);
  }

  rmSync(join(DEST, "contracts"), { recursive: true, force: true }); // clean-slate rebuild — no orphaned sidecar for a removed spec (#64; see header)
  mkdirSync(join(DEST, "contracts"), { recursive: true });
  for (const s of specs) {
    if (s.head.contract) copyFileSync(join(SPECS, s.head.contract), join(DEST, "contracts", s.head.contract));
  }
  copyFileSync(join(ROOT, "system/tokens.source.json"), join(DEST, "tokens.dtcg.json"));

  // Portability proofs (#12): wrapper modules + README travel with the pack; demo.html
  // does not (it references absolute /system/ paths — the wc README links the live demo).
  const wcFiles = existsSync(WC_SRC)
    ? readdirSync(WC_SRC).filter((f) => f.endsWith(".mjs")).sort()
    : [];
  if (!wcFiles.length) throw new Error(`${WC_SRC}: no wrapper modules found — did system/wc/ move?`);
  if (!existsSync(join(WC_SRC, "README.md"))) throw new Error(`${WC_SRC}/README.md: missing — the pack ships the wrapper doc`);
  if (!existsSync(FIGMA_DOC)) throw new Error(`${FIGMA_DOC}: missing — the pack ships the Figma import doc`);
  rmSync(join(DEST, "wc"), { recursive: true, force: true }); // clean-slate rebuild — no orphaned wrapper for a removed wc module (#64; see header)
  mkdirSync(join(DEST, "wc"), { recursive: true });
  for (const f of [...wcFiles, "README.md"]) copyFileSync(join(WC_SRC, f), join(DEST, "wc", f));
  copyFileSync(FIGMA_DOC, join(DEST, "figma-import.md"));

  const pack = {
    $description:
      "Verdant handoff pack — ComponentSpecs (machine head + prose sections), DataContracts (JSON Schema 2020-12), and the DTCG token source with css/ios/android builds. Verdant is a fictional demo scenario. Generated by agent-layer/gen-handoff.mjs from system/specs/ — do not edit.",
    scenario: "verdant",
    generatedFrom: "system/specs",
    components: specs.map((s) => ({
      ...s.head,
      contract: s.head.contract ? `contracts/${s.head.contract}` : null,
      sections: s.sections,
    })),
    portability: {
      webComponents: {
        files: wcFiles.map((f) => `wc/${f}`),
        readme: "wc/README.md",
        trajectory:
          "every component ships as a standalone custom element, themed by the token contract alone; the canonical handoff form remains copy-paste HTML/CSS reading only semantic tokens",
      },
      figma: {
        import: "figma-import.md",
        // Written only by a real run of tooling/figma/figma-parity.mjs — null until
        // then (rendered as "pending real run"); never a placeholder file.
        parity: existsSync(join(DEST, "figma-parity.json")) ? "figma-parity.json" : null,
      },
    },
  };
  writeFileSync(join(DEST, "pack.json"), JSON.stringify(pack, null, 2) + "\n");

  return { components: specs.length, targets: 3, wrappers: wcFiles.length, dest: DEST };
}

// pathToFileURL, not `file://${argv[1]}`: this repo's path contains a space, which
// import.meta.url percent-encodes — the naive comparison never matches.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const r = genHandoff();
  console.log(`handoff pack    ✓  ${r.components} specs + ${r.targets} token targets + ${r.wrappers} wc wrappers (handoff/verdant)`);
}
