// gen-handoff.mjs — ComponentSpecs + DataContracts + tokens → the handoff pack
// (epic #1, ticket #7). Spec: docs/epics/ai-first-ux-factory.architecture.md §Data model.
// Emits handoff/verdant/: pack.json (spec heads + prose, inlined for the viewer),
// verbatim DataContracts, the DTCG source, and Style Dictionary css/ios/android builds.
// Standalone:  node agent-layer/gen-handoff.mjs
// Paths resolve from this module (NOT cwd) — build.mjs runs from the jobs folder.

import { copyFileSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { execFileSync } from "node:child_process";
import { parseComponentSpec } from "./lib.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const SPECS = join(ROOT, "system/specs");
const DEST = join(ROOT, "handoff/verdant");
const SD_BUILD = join(ROOT, "tooling/style-dictionary/build-tokens.mjs");

export function genHandoff() {
  const files = readdirSync(SPECS).filter((f) => f.endsWith(".md")).sort();
  const specs = files.map((f) => parseComponentSpec(join(SPECS, f)));

  const names = new Set(specs.map((s) => s.head.component));
  for (const s of specs) {
    for (const child of s.head.children) {
      if (!names.has(child)) throw new Error(`${s.path}: children entry "${child}" names no spec in system/specs/`);
    }
  }

  // Multi-target token builds — child process so agent-layer stays zero-dep
  // (tooling/style-dictionary owns the one allowed dependency).
  try {
    execFileSync(process.execPath, [SD_BUILD], { stdio: "inherit" });
  } catch {
    throw new Error(`${SD_BUILD}: Style Dictionary build failed — if node_modules is missing, run: cd tooling/style-dictionary && npm install`);
  }

  mkdirSync(join(DEST, "contracts"), { recursive: true });
  for (const s of specs) {
    if (s.head.contract) copyFileSync(join(SPECS, s.head.contract), join(DEST, "contracts", s.head.contract));
  }
  copyFileSync(join(ROOT, "system/tokens.source.json"), join(DEST, "tokens.dtcg.json"));

  const pack = {
    $description:
      "Verdant handoff pack — ComponentSpecs (machine head + prose sections), DataContracts (JSON Schema 2020-12), and the DTCG token source with css/ios/android builds. Verdant is a fictional demo scenario. Generated by agent-layer/gen-handoff.mjs from system/specs/ — do not edit.",
    scenario: "verdant",
    generatedFrom: "system/specs",
    components: specs.map((s) => ({
      ...s.head,
      contract: s.head.contract ? `contracts/${s.head.contract}` : null,
      sections: s.sections,
    })),
  };
  writeFileSync(join(DEST, "pack.json"), JSON.stringify(pack, null, 2) + "\n");

  return { components: specs.length, targets: 3, dest: DEST };
}

// pathToFileURL, not `file://${argv[1]}`: this repo's path contains a space, which
// import.meta.url percent-encodes — the naive comparison never matches.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const r = genHandoff();
  console.log(`handoff pack    ✓  ${r.components} specs + ${r.targets} token targets (handoff/verdant)`);
}
