// tooling/import-suggest.mjs — the operator CLI for the design importer's machine suggestions (#455),
// over the SAME suggest() the two import routes run (portal/lib/import-suggest.mjs). It reads spike C's
// two committed blueprint reads (owner, 2026-09-27, Q2) and never touches a run package.
//
//   node tooling/import-suggest.mjs                     FREE. Each read through the real pipeline: the
//        unnamed paths, each node's state exactly as it would be sent, the option count, templateSha and
//        the estimated tokens per question. No call.
//   node tooling/import-suggest.mjs --smoke             PAID (≈ $0.0007). The instance read's FIRST
//        unnamed node alone, one request: prints usage.input_tokens, the latency and the top 3, and exits
//        1 when input_tokens is missing or over MAX_ACCEPTED (the largest request observed accepted, plan
//        R1). Writes nothing; never scored.
//   node tooling/import-suggest.mjs --run               PAID (≈ $0.0057). suggest() over both reads, with
//        an `ask` that records every request body as sent and every response verbatim. Retries 429/529
//        only (2 s, 4 s, 8 s); any other failure WRITES NOTHING and exits 1. Refuses when the run file
//        already exists: one completed run is the result — never re-run for a better answer.
//   node tooling/import-suggest.mjs --labels-template   FREE. Writes tooling/import-suggest/labels.json,
//        one row per suggested node with `label: null`, for the OWNER to fill (a slug or "none", then
//        `by` and `at`). Refuses to overwrite a file whose `by` is set. The session never writes a label.
//   node tooling/import-suggest.mjs --report            FREE. With the owner's labels in: per node the
//        label, Jev's top 3, top-1 and in-top-3, and the totals. Without them it says so and exits 0.
//
// Any other --flag is refused by name, so a typo never falls through to a paid mode.
//
// The run file is GENERATED from real API responses. Never hand-edit it (honesty contract): build-checks
// group 46 replays it and checks templateSha, both fixtures' sha256 and every request's node state.
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { askJev, JEV_MODEL } from "../portal/lib/jev.mjs";
import { loadInputs, runPipeline } from "../portal/lib/import-run.mjs";
import { walk } from "../import/ir.mjs";
import {
  MAX_IN_FLIGHT, NONE, parseAnswer, questionsFor, suggest, SUGGEST_TIMEOUT_MS, TEMPLATE, unnamedPaths,
} from "../portal/lib/import-suggest.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
export const READS = Object.freeze(["import/fixtures/spike-c-instance.blueprint.txt", "import/fixtures/spike-c-master.blueprint.txt"]);
export const RUN_FILE = "tooling/import-suggest/spike-c-run.json";
export const LABELS_FILE = "tooling/import-suggest/labels.json";
export const MAX_ACCEPTED = 38875;   // discovery-screen.mjs's largest request observed accepted (plan R1)
export const NOTE = "GENERATED by tooling/import-suggest.mjs from real TypeSafe API responses — never edit; re-run instead. What it cannot show: whether the ranking is right (the owner's labels.json and --report) or the live API today.";
const PRICE_PER_M = 0.042;           // jev-1.13.0's input price per million tokens (#454's header: UNVERIFIED in TypeSafe's docs)
const sha256 = (s) => createHash("sha256").update(s).digest("hex");
export const templateSha = () => sha256(JSON.stringify(TEMPLATE));
export const fixtureName = (f) => basename(f).replace(/\.blueprint\.txt$/, "");

// The owner's labels, checked against the run they label. Pure; throws naming the row.
export function checkLabels(labels, run, vocabSlugs) {
  if (!labels || typeof labels !== "object") throw new Error("labels: expected an object");
  if (labels.by !== null && (typeof labels.by !== "string" || !labels.by)) throw new Error(`labels.by: ${JSON.stringify(labels.by)} — null until the owner labels, then their name`);
  if (!Array.isArray(labels.nodes)) throw new Error("labels.nodes: expected an array");
  const want = (run?.reads ?? []).flatMap((r) => r.suggestions.map((s) => `${r.fixture} ${s.path}`));
  const got = labels.nodes.map((n) => `${n?.fixture} ${n?.path}`);
  if (JSON.stringify(got) !== JSON.stringify(want)) throw new Error(`labels.nodes: the rows are ${JSON.stringify(got)}, the run's suggested nodes are ${JSON.stringify(want)}`);
  const allowed = [...vocabSlugs, NONE];
  labels.nodes.forEach((n) => {
    const at = `${fixtureName(n.fixture)} ${n.path}`;
    if (labels.by === null && n.label !== null) throw new Error(`labels: label ${JSON.stringify(n.label)} at ${at} is set while by is null — the owner labels, then signs`);
    if (labels.by !== null && !allowed.includes(n.label)) throw new Error(`labels: label ${n.label} at ${at} is not a slug or "none"`);
  });
  return labels;
}

const die = (msg) => { console.error(`import-suggest: ${msg}`); process.exit(1); };
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// 429/529 only; any other failure is the answer. `ms` is the successful attempt, not the backoff.
async function retrying(call) {
  for (const wait of [2000, 4000, 8000, null]) {
    const t0 = performance.now();
    try {
      const r = await call();
      return { r, ms: Math.round(performance.now() - t0) };
    } catch (e) {
      const status = e.message.match(/^jev: (\d{3}) /)?.[1];
      if (wait === null || (status !== "429" && status !== "529")) throw e;
      await sleep(wait);
    }
  }
}

// An ask that keeps the request body AS SENT (the fetch's own string, model included) and the response.
const recordingAsk = (log) => async (body, opts) => {
  const id = Object.keys(body.questions)[0];
  let sent = null;
  const fetchImpl = (url, init) => { sent = init.body; return fetch(url, init); };
  const { r, ms } = await retrying(() => askJev(body, { ...opts, fetchImpl }));
  log.push({ id, body: JSON.parse(sent), response: r, ms });
  return r;
};

function pipeFor(fixture, inputs) {
  const text = readFileSync(join(ROOT, fixture), "utf8");
  return { text, pipe: runPipeline({ text, tool: "brilliant", ...inputs }) };
}

function nodesByPath(ir) {
  const m = new Map();
  walk(ir, (n, p) => m.set(p, n));
  return m;
}

async function main() {
  const argv = process.argv.slice(2);
  const FLAGS = ["--smoke", "--run", "--labels-template", "--report"];
  for (const a of argv) if (!FLAGS.includes(a)) die(`unknown argument ${a} — the flags are ${FLAGS.join(" ")}`);
  if (argv.length > 1) die(`one mode at a time — got ${argv.join(" ")}`);
  const mode = argv[0] ?? null;
  const inputs = loadInputs();
  const vocabSlugs = Object.keys(inputs.vocab.components);

  if (mode === null) {
    let total = 0;
    for (const f of READS) {
      const { pipe } = pipeFor(f, inputs);
      const { questions, paths } = questionsFor(pipe.ir, pipe.verdict, inputs.vocab);
      console.log(`\n${f}: ${Object.keys(questions).length} unnamed`);
      for (const [id, q] of Object.entries(questions)) {
        const est = Math.ceil(JSON.stringify(q).length / 1.7);
        total += est;
        const leak = /\b[0-9a-f]{16}\b|#[0-9a-fA-F]{6}\b/.test(JSON.stringify(q.instructions.node));
        console.log(`  ${id} ${paths[id]}  ≈ ${est} tokens${leak ? "  LEAK: an id or a colour is in the state" : ""}`);
        console.log(`     ${JSON.stringify(q.instructions.node)}`);
      }
      if (Object.keys(questions).length) console.log(`  options: ${Object.keys(Object.values(questions)[0].criteria).length}`);
    }
    console.log(`\ntemplateSha ${templateSha()} · model ${JEV_MODEL} · ≈ ${total} tokens in all ≈ $${(total * PRICE_PER_M / 1e6).toFixed(4)}`);
    console.log(`a paid --run would write ${RUN_FILE}${existsSync(join(ROOT, RUN_FILE)) ? " — it EXISTS, so --run refuses" : ""}`);
    return;
  }

  if (mode === "--smoke") {
    const { pipe } = pipeFor(READS[0], inputs);
    const { questions, paths } = questionsFor(pipe.ir, pipe.verdict, inputs.vocab);
    const q = questions.n0;
    if (!q) die(`${READS[0]} has no unnamed node`);
    const { r, ms } = await retrying(() => askJev({ state: { task: "design import" }, questions: { n0: q } }, { timeoutMs: SUGGEST_TIMEOUT_MS })).catch((e) => die(e.message));
    const tokens = r.usage?.input_tokens;
    const { top, confidence } = parseAnswer(r.answers?.n0, Object.keys(q.criteria), "answers.n0");
    console.log(`smoke ${paths.n0}: input_tokens ${tokens}, output_tokens ${r.usage?.output_tokens}, ${ms} ms, model ${r.model}`);
    console.log(`  top 3: ${top.map((t) => `${t.slug} ${t.p}`).join(", ")} · confidence ${confidence}`);
    if (!Number.isFinite(tokens)) die(`the response carries no usage.input_tokens (${JSON.stringify(r.usage)}) — the size check cannot run`);
    if (tokens > MAX_ACCEPTED) die(`one node is ${tokens} tokens, over the ${MAX_ACCEPTED} largest-accepted — stop and bring this to the owner`);
    console.log(`  under ${MAX_ACCEPTED}: yes · estimated cost $${(tokens * PRICE_PER_M / 1e6).toFixed(5)}`);
    return;
  }

  if (mode === "--run") {
    if (existsSync(join(ROOT, RUN_FILE))) die(`${RUN_FILE} exists — one completed run is the result; never re-run for a better answer`);
    const reads = [];
    for (const f of READS) {
      const { text, pipe } = pipeFor(f, inputs);
      const log = [];
      const out = await suggest({ ir: pipe.ir, verdict: pipe.verdict, vocab: inputs.vocab }, { ask: recordingAsk(log), inFlight: MAX_IN_FLIGHT });
      if (!out.ran) die(`${f}: ${out.reason} — nothing written`);
      log.sort((a, b) => Number(a.id.slice(1)) - Number(b.id.slice(1)));
      reads.push({ fixture: f, fixtureSha256: sha256(text), requests: log, suggestions: out.suggestions });
      console.log(`${f}: ${out.suggestions.length} suggestions over ${out.requests} requests, usage ${JSON.stringify(out.usage)}`);
    }
    const over = reads.flatMap((r) => r.requests).filter((q) => !(q.response?.usage?.input_tokens <= MAX_ACCEPTED));
    if (over.length) die(`${over.map((q) => q.id).join(", ")} carried no usage or ran over ${MAX_ACCEPTED} tokens — nothing written`);
    mkdirSync(dirname(join(ROOT, RUN_FILE)), { recursive: true });
    writeFileSync(join(ROOT, RUN_FILE), `${JSON.stringify({ note: NOTE, model: JEV_MODEL, templateSha: templateSha(), inFlight: MAX_IN_FLIGHT, at: new Date().toISOString(), reads }, null, 2)}\n`);
    for (const r of reads) for (const s of r.suggestions) {
      console.log(`  ${fixtureName(r.fixture)} ${s.path}: ${s.top.map((t) => `${t.slug} ${t.p}`).join(", ")} · confidence ${s.confidence}`);
    }
    console.log(`wrote ${RUN_FILE}`);
    return;
  }

  const runPath = join(ROOT, RUN_FILE);
  if (!existsSync(runPath)) die(`${RUN_FILE} is missing — run --run first (needs TYPESAFE_API_KEY)`);
  const run = JSON.parse(readFileSync(runPath, "utf8"));

  if (mode === "--labels-template") {
    const lp = join(ROOT, LABELS_FILE);
    if (existsSync(lp) && JSON.parse(readFileSync(lp, "utf8")).by !== null) die(`${LABELS_FILE} is signed by the owner — refusing to overwrite it`);
    const nodes = [];
    for (const r of run.reads) {
      const byPath = nodesByPath(pipeFor(r.fixture, inputs).pipe.ir);
      for (const s of r.suggestions) nodes.push({ fixture: r.fixture, path: s.path, layer: byPath.get(s.path)?.name ?? null, kind: byPath.get(s.path)?.kind ?? null, label: null, note: "" });
    }
    const labels = checkLabels({ by: null, at: null, nodes }, run, vocabSlugs);
    writeFileSync(lp, `${JSON.stringify(labels, null, 2)}\n`);
    console.log(`wrote ${LABELS_FILE}: ${nodes.length} rows for the owner`);
    return;
  }

  if (mode === "--report") {
    const labels = checkLabels(JSON.parse(readFileSync(join(ROOT, LABELS_FILE), "utf8")), run, vocabSlugs);
    if (labels.by === null) { console.log("the owner has not labelled — fill labels.json (label, by, at), then re-run --report"); return; }
    const sug = new Map(run.reads.flatMap((r) => r.suggestions.map((s) => [`${r.fixture} ${s.path}`, s])));
    let top1 = 0, top3 = 0;
    for (const n of labels.nodes) {
      const s = sug.get(`${n.fixture} ${n.path}`);
      const hit1 = s.top[0].slug === n.label, hit3 = s.top.some((t) => t.slug === n.label);
      top1 += hit1; top3 += hit3;
      console.log(`${fixtureName(n.fixture)} ${n.path} (${n.layer}): owner ${n.label} · Jev ${s.top.map((t) => `${t.slug} ${t.p}`).join(", ")} · top-1 ${hit1 ? "yes" : "no"} · in top 3 ${hit3 ? "yes" : "no"}`);
    }
    const nones = labels.nodes.filter((n) => sug.get(`${n.fixture} ${n.path}`).top[0].slug === NONE);
    console.log(`\ntop-1 ${top1}/${labels.nodes.length} · in top 3 ${top3}/${labels.nodes.length} · labelled by ${labels.by} at ${labels.at}`);
    console.log(`none as the top pick: ${nones.length ? nones.map((n) => `${fixtureName(n.fixture)} ${n.path}`).join(", ") : "none"}`);
  }
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) await main();
