// tooling/jev-screen.mjs — the #453 contradiction screen's operator CLI, over the SAME functions the
// portal's audit route runs (portal/lib/discovery-screen.mjs). It never touches a run package.
//
// Four modes:
//   node tooling/jev-screen.mjs <document.md> --claims   FREE. Prints the split; for the frozen fixture
//        only (md5 below) writes tooling/jev-screen/fixture-claims.json — the committed claim ids the
//        screen rubric and build-checks 45.2 read.
//   node tooling/jev-screen.mjs <document.md> --smoke    PAID (≈ $0.0005). Stage 1 over the first three
//        claims (full state) and stage 2 over c001 ↔ c002, one request each: proves the request shape
//        and measures latency before a full run. Writes nothing; its answers are never scored.
//   node tooling/jev-screen.mjs <document.md>            PAID (≈ $0.01). The full screen. Retries 429/529
//        only (2 s, 4 s, 8 s); any other failure aborts and WRITES NOTHING. For the frozen fixture only,
//        writes tooling/jev-screen/screen-run.json — the verbatim responses build-checks 45.8 replays.
//   node tooling/jev-screen.mjs --labels-template        FREE. Writes tooling/jev-screen/labels.json with
//        every kept pair of both screens and `real: null`, for the OWNER to fill. Refuses to overwrite a
//        file whose `by` is set. The session never writes a verdict.
//
// screen-run.json is GENERATED from real API responses. Never hand-edit it (honesty contract): an
// edited question wording moves questionsSha, which 45.8 checks. One completed run is the result —
// never re-run for a better score.
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { askJev, JEV_MODEL } from "../portal/lib/jev.mjs";
import { CLAIMS_VERSION, splitClaims } from "../discovery/claims.mjs";
import {
  batches, estTokens, QUESTION_TEMPLATES, readScreen, REQUEST_TOKEN_BUDGET, SCREEN_TIMEOUT_MS,
  screenDocument, stage1Question, stage1State, stage2Questions, tensionsOf,
} from "../portal/lib/discovery-screen.mjs";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DIR = join(ROOT, "tooling/jev-screen");
export const FIXTURE_MD5 = "ab6eb0ee6cdd3b7802ecfcbe90db2377";
const PRICE_PER_M = 0.042; // the Models page's input price for jev-1.13.0; output is free
const GENERATED = "GENERATED by tooling/jev-screen.mjs from real TypeSafe API responses — never edit; re-run instead";
const md5 = (s) => createHash("md5").update(s).digest("hex");
const sha256 = (s) => createHash("sha256").update(s).digest("hex");
export const questionsSha = () => sha256(JSON.stringify(QUESTION_TEMPLATES));
const die = (msg) => { console.error(`jev-screen: ${msg}`); process.exit(1); };

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
// Each call's `ms` is its SUCCESSFUL attempt only; backoff sleeps are not Jev latency.
const timed = [];
async function ask(body, opts) {
  for (const wait of [2000, 4000, 8000, null]) {
    const t0 = performance.now();
    try {
      const r = await askJev(body, opts);
      timed.push(Math.round(performance.now() - t0));
      return r;
    } catch (e) {
      const status = e.message.match(/^jev: (\d{3}) /)?.[1];
      if (wait === null || (status !== "429" && status !== "529")) throw e;
      await sleep(wait);
    }
  }
}

const argv = process.argv.slice(2);
const flag = (f) => argv.includes(f);
const docArg = argv.find((a) => !a.startsWith("--"));

if (flag("--labels-template")) {
  const out = join(DIR, "labels.json");
  if (existsSync(out) && JSON.parse(readFileSync(out, "utf8")).by) die(`${relative(ROOT, out)} carries the owner's verdicts (by is set) — refusing to overwrite it`);
  const runFile = join(DIR, "screen-run.json");
  if (!existsSync(runFile)) die("no tooling/jev-screen/screen-run.json — run the paid screen first");
  const row = ({ a, b }) => ({ a, b, real: null, note: "" });
  const screens = { "screen-run": tensionsOf(JSON.parse(readFileSync(runFile, "utf8")).lines).map(row) };
  const pkg = join(ROOT, "discovery/partner-audit-3");
  if (existsSync(join(pkg, "screen.jsonl"))) screens["partner-audit-3"] = tensionsOf(readScreen(pkg)).map(row);
  writeFileSync(out, `${JSON.stringify({ by: null, at: null, screens }, null, 2)}\n`);
  console.log(`jev-screen ✓ wrote ${relative(ROOT, out)} — ${Object.entries(screens).map(([k, v]) => `${k}: ${v.length} pair(s)`).join(" · ")}. The owner sets real (true|false), by: "owner" and at.`);
  process.exit(0);
}

if (!docArg) die("usage: node tooling/jev-screen.mjs <document.md> [--claims | --smoke] | --labels-template");
const docPath = resolve(docArg);
const text = readFileSync(docPath, "utf8");
const docMd5 = md5(text);
const isFixture = docMd5 === FIXTURE_MD5;
const claims = splitClaims(text);

if (flag("--claims")) {
  console.log(`claims: ${claims.length} · md5 ${docMd5} · version ${CLAIMS_VERSION}`);
  if (!isFixture) { console.log("not the frozen fixture — nothing written"); process.exit(0); }
  const out = join(DIR, "fixture-claims.json");
  writeFileSync(out, `${JSON.stringify({
    $description: "GENERATED by tooling/jev-screen.mjs --claims from the frozen fixture — never edit; re-run instead",
    source: relative(ROOT, docPath), md5: docMd5, claimsVersion: CLAIMS_VERSION, claims,
  }, null, 2)}\n`);
  console.log(`jev-screen ✓ wrote ${relative(ROOT, out)}`);
  process.exit(0);
}

if (flag("--smoke")) {
  const state = stage1State(claims);
  const qs1 = {};
  for (const c of claims.slice(0, 3)) qs1[`pick_${c.id}`] = stage1Question(c, claims);
  const est1 = estTokens(state) + Object.values(qs1).reduce((s, q) => s + estTokens(q), 0);
  // A second stage-1 request with 30 questions: the option-heavy JSON is what overflowed the estimate,
  // and two usage figures solve for per-state and per-question tokens. Its answers are not printed.
  const qs30 = {};
  for (const c of claims.slice(3, 33)) qs30[`pick_${c.id}`] = stage1Question(c, claims);
  const est30 = estTokens(state) + Object.values(qs30).reduce((s, q) => s + estTokens(q), 0);
  let r1, r2, r30;
  try {
    r1 = await ask({ state, questions: qs1 }, { timeoutMs: SCREEN_TIMEOUT_MS });
    r2 = await ask({ state: QUESTION_TEMPLATES.stage2State, questions: stage2Questions(claims[0], claims[1]) }, { timeoutMs: SCREEN_TIMEOUT_MS });
    r30 = await ask({ state, questions: qs30 }, { timeoutMs: SCREEN_TIMEOUT_MS });
  } catch (e) { die(e.message); }
  const u3 = r1.usage?.input_tokens, u30 = r30.usage?.input_tokens;
  const perQ = (u30 - u3) / 27, perState = u3 - 3 * perQ;
  const ch = (x) => JSON.stringify(x).length;
  const avgQChars = Object.values(qs30).reduce((s, q) => s + ch(q), 0) / 30;
  console.log(`calibration: 3 questions ${u3} tok (est ${est1}) · 30 questions ${u30} tok (est ${est30}) · per question ${perQ.toFixed(0)} tok for ${avgQChars.toFixed(0)} chars (${(avgQChars / perQ).toFixed(2)} chars/token) · state ${perState.toFixed(0)} tok for ${ch(state)} chars (${(ch(state) / perState).toFixed(2)} chars/token) · 30-question request ${timed[2]} ms`);
  for (const id of Object.keys(qs1)) {
    const a = r1.answers?.[id];
    if (typeof a?.choice !== "string" || !Number.isFinite(a.probabilities?.[a.choice])) die(`smoke: ${id} came back without choice + probabilities — ${JSON.stringify(a)}`);
    console.log(`${id} → ${a.choice} p ${a.probabilities[a.choice]} · confidence ${a.confidence}`);
  }
  const rel = r2.answers?.[`relation_${claims[0].id}_${claims[1].id}`];
  const same = r2.answers?.[`same_${claims[0].id}_${claims[1].id}`];
  if (!Number.isFinite(rel?.probabilities?.contradicts)) die(`smoke: relation came back without probabilities.contradicts — ${JSON.stringify(rel)}`);
  if (!Number.isFinite(same?.noul)) die(`smoke: same_subject came back without a noul — ${JSON.stringify(same)}`);
  console.log(`relation → ${rel.choice} ${JSON.stringify(rel.probabilities)} · same_subject noul ${same.noul}`);
  // The pre-registered latency rule (plan Task 16b, R3), per REQUEST, since the timeout is per request.
  const qsAll = {};
  for (const c of claims) qsAll[`pick_${c.id}`] = stage1Question(c, claims);
  const largest = Math.max(...batches(qsAll, state).map((b) => estTokens(state) + Object.values(b).reduce((s, q) => s + estTokens(q), 0)));
  const projected = Math.round(timed[0] * (largest / est1));
  console.log(`latency rule: ${timed[0]} ms × (largest stage-1 request est ${largest} ÷ smoke est ${est1}) = ${projected} ms projected vs ${SCREEN_TIMEOUT_MS / 2} ms (half of SCREEN_TIMEOUT_MS) at REQUEST_TOKEN_BUDGET ${REQUEST_TOKEN_BUDGET} → ${projected > SCREEN_TIMEOUT_MS / 2 ? "HALVE the budget" : "fits"}`);
  console.log(`smoke ✓ shape ok · stage1 ${timed[0]} ms / ${r1.usage?.input_tokens} tok (est ${est1}) · stage2 ${timed[1]} ms / ${r2.usage?.input_tokens} tok`);
  process.exit(0);
}

// The paid run.
const ranAt = new Date().toISOString();
let result;
try { result = await screenDocument(text, { ask }); } catch (e) { die(`${e.message} — nothing written`); }
const { lines, requests } = result;
const summary = lines.at(-1);
for (const t of tensionsOf(lines)) {
  const pair = lines.find((l) => l.type === "pair" && l.a.id === t.a.id && l.b.id === t.b.id);
  console.log(`${t.a.id} ↔ ${t.b.id}  contradicts ${t.contradicts.toFixed(2)}  same ${pair.sameSubject.toFixed(2)}`);
  console.log(`  ${t.a.id} (${t.a.section}): ${t.a.text}`);
  console.log(`  ${t.b.id} (${t.b.section}): ${t.b.text}`);
}
const est = requests.filter((r) => r.stage === 1).map((r) => estTokens(stage1State(claims))
  + r.questionIds.reduce((s, id) => s + estTokens(stage1Question(claims.find((c) => `pick_${c.id}` === id), claims)), 0));
const sorted = [...timed].sort((a, b) => a - b);
const n1 = requests.filter((r) => r.stage === 1).length;
console.log(`claims ${summary.claims} · picks ${summary.picks} · candidates ${summary.candidates} · kept ${summary.kept} · t1 ${summary.t1}`);
console.log(`requests ${requests.length} (stage 1: ${n1}, stage 2: ${requests.length - n1}) · input tokens ${summary.inputTokens} (observed, usage) · est. stage-1 tokens ${est.reduce((s, e) => s + e, 0)} · cost $${summary.inputTokens === null ? "?" : (summary.inputTokens * PRICE_PER_M / 1e6).toFixed(5)} (derived: tokens × $${PRICE_PER_M}/M) · latency p50 ${sorted[Math.ceil(sorted.length / 2) - 1]} ms, max ${sorted.at(-1)} ms`);
if (!isFixture) { console.log("not the frozen fixture — nothing written"); process.exit(0); }
const out = join(DIR, "screen-run.json");
writeFileSync(out, `${JSON.stringify({
  $description: GENERATED, model: JEV_MODEL, ranAt, docMd5, claimsVersion: CLAIMS_VERSION, questionsSha: questionsSha(),
  requests: requests.map((r, i) => ({ ...r, ms: timed[i] })), lines,
}, null, 2)}\n`);
console.log(`jev-screen ✓ wrote ${relative(ROOT, out)}`);
